"""Text shared by every landing page (labels, footer, disclaimer)."""
OPTIONAL_REGEX = True  # generic patterns; not every page has all of them
REGEX = [
    (r"من ([\d,]+) إلى ([\d,]+) م²", r"\1–\2 m²"),
    (r"من (\d+) إلى (\d+) غرف", r"\1–\2"),
    (r">(\d+) غرف<", r">\1<"),
    (r">([\d,]+) م²<", r">\1 m²<"),
    (r"([\d,]{7,}) ج\.م", r"EGP \1"),
    (r'aria-label="صورة (\d+)"', r'aria-label="Image \1"'),
]
STRINGS = {
    '"name": "الرئيسية"': '"name": "Home"',
    "مقدم يبدأ من": "Down payment from",
    "سنوات تقسيط": "Years of installments",
    "تبدأ الأسعار من (ج.م)": "Prices from (EGP)",
    "تبدأ الأسعار (ج.م)": "Prices from (EGP)",
    "احصل على قائمة الأسعار": "Get the price list",
    "سيبلنا بياناتك ونبعتلك أحدث الأسعار وأنظمة التقسيط خلال دقائق": "Leave your details and we will send you the latest prices and payment plans within minutes",
    "إشعار الكوكيز": "Cookie notice",
    "اختار نوع الوحدة اللي يناسبك واطلب أحدث الأسعار وأنظمة التقسيط": "Pick the unit type that suits you and request the latest prices and payment plans",
    "متشطبة بالكامل": "Fully finished",
    "الأسعار تبدأ من": "Prices from",
    "المساحة": "Area",
    "الغرف": "Bedrooms",
    "الأسعار وخطط السداد": "Prices and payment plans",
    "الأسعار والمساحات وأنظمة السداد الموضحة استرشادية وقابلة للتغيير من المطور دون إشعار مسبق.": "Prices, areas and payment plans shown are indicative and may be changed by the developer without notice.",
    "عن المشروع": "About the project",
    "م² نطاق المساحات": "m² unit sizes",
    "المرافق والخدمات": "Facilities and services",
    "الموقع والماستر بلان": "Location and master plan",
    "قريب من": "Close to",
    "معرض الصور": "Photo gallery",
    "اتفرّج على صور المشروع من كل الزوايا": "See the project from every angle",
    "السابق": "Previous",
    "التالي": "Next",
    "عرض الصورة": "Image viewer",
    "أسئلة شائعة": "FAQ",
    "حدّد ميزانيتك": "Set your budget",
    "هنتواصل معاك خلال دقائق — من غير أي رسوم أو التزام.": "We will contact you within minutes — no fees and no obligation.",
    "مشاريع أخرى": "Other projects",
    "اكتشف باقي مشاريع مراكز": "Explore more Marakez projects",
    "اعرف التفاصيل ←": "View details →",
    "مشروع Crescent Walk من مراكز — التجمع السادس": "Crescent Walk by Marakez — 6th Settlement",
    "مشروع District 5 من مراكز — القاهرة الجديدة": "District 5 by Marakez — New Cairo",
    "مشروع Shams Soma من مراكز — سوما باي، البحر الأحمر": "Shams Soma by Marakez — Soma Bay, Red Sea",
    "مشروع Ramla من مراكز — رأس الحكمة، الساحل الشمالي": "Ramla by Marakez — Ras El Hekma, North Coast",
    "سوما باي — البحر الأحمر": "Soma Bay — Red Sea",
    "رأس الحكمة — الساحل الشمالي": "Ras El Hekma — North Coast",
    "التجمع السادس": "6th Settlement",
    "القاهرة الجديدة": "New Cairo",
    "منصة إعلامية تسويقية عقارية مستقلة، يملكها ويديرها": "is an independent real estate marketing and media platform, owned and operated by",
    "منصة إعلامية تسويقية عقارية مستقلة": "An independent real estate marketing platform",
    "تواصل واتساب": "Chat on WhatsApp",
    "%D9%85%D8%B1%D8%AD%D8%A8%D8%A7%D8%8C%20%D8%B9%D8%A7%D9%88%D8%B2%20%D8%A7%D8%B3%D8%AA%D9%81%D8%B3%D8%B1": "Hello%2C%20I%20have%20a%20question",
    "إخلاء مسؤولية": "Disclaimer",
    "المسوّق العقاري": "real estate marketer",
    ". المنصة ليست الجهة المطوّرة أو المالكة للمشاريع": ". The platform is not the developer or owner of the projects",
    "المعروضة، وجميع أسماء وشعارات المشاريع والمطوّرين مملوكة لأصحابها وتُستخدم لأغراض العرض والتعريف فقط.": "shown here. All project and developer names and logos belong to their owners and are used for presentation and identification only.",
    "كافة البيانات من أسعار ومساحات وأنظمة سداد وصور ومواعيد تسليم هي": "All information, including prices, areas, payment plans, images and delivery dates, is",
    "لأغراض استرشادية فقط": "for guidance only",
    "</strong>،\n": "</strong>,\n",
    "وقابلة للتغيير من قِبل المطوّر في أي وقت دون إشعار مسبق، ولا تُعد عرضاً أو التزاماً تعاقدياً.": "and may be changed by the developer at any time without notice. It is not an offer or a contractual commitment.",
    "يُرجى الرجوع للمطوّر الرسمي لاعتماد الأسعار والتفاصيل النهائية قبل اتخاذ أي قرار شرائي.": "Please confirm final prices and details with the official developer before making any purchase decision.",
    ">المشاريع<": ">Projects<",
    'aria-label="المشاريع"': 'aria-label="Projects"',
    "Ramla رأس الحكمة<": "Ramla Ras El Hekma<",
    "District 5 القاهرة الجديدة<": "District 5 New Cairo<",
    "Crescent Walk التجمع السادس<": "Crescent Walk 6th Settlement<",
    "Shams Soma سوما باي<": "Shams Soma Soma Bay<",
    "مشاريع ORA القاهرة الجديدة<": "ORA Projects New Cairo<",
    "— جميع الحقوق محفوظة.": "— All rights reserved.",
    "سياسة الخصوصية": "Privacy Policy",
    "<strong>مراكز</strong>": "<strong>Marakez</strong>",
    "فدان مساحة المشروع": "feddans project area",
    "أبرز المرافق": "Key facilities",
    # unit types
    "شاليهات": "Chalets",
    "تاون هاوس": "Townhouses",
    "توين هاوس": "Twin Houses",
    "فيلات مستقلة": "Standalone Villas",
    "شقق": "Apartments",
}
