"""English text for crescent-walk.html."""
REGEX = [
    (r"شقق وفيلات كريسنت ووك \(Crescent Walk\) من مراكز في التجمع السادس، القاهرة الجديدة — مقدم (\d+)% وتقسيط حتى (\d+) سنين\. اطلب أحدث الأسعار وتفاصيل الوحدات المتاحة الآن\.",
     r"Crescent Walk by Marakez in the 6th Settlement, New Cairo: apartments and villas with a \1% down payment and installments up to \2 years. Request the latest prices and available units."),
    (r"وحدات كريسنت ووك: شقق من (\d+) إلى (\d+) م² \((\d+) إلى (\d+) غرف\)، تاون هاوس (\d+) م² \((\d+) غرف\)، توين هاوس من (\d+) إلى (\d+) م² \((\d+) غرف\)، وفيلات مستقلة من (\d+) إلى (\d+) م² \((\d+) إلى (\d+) غرف\)\.",
     r"Crescent Walk offers apartments from \1 to \2 m² (\3 to \4 bedrooms), townhouses of \5 m² (\6 bedrooms), twin houses from \7 to \8 m² (\9 bedrooms) and standalone villas from \10 to \11 m² (\12 to \13 bedrooms)."),
    (r"أسعار شقق كريسنت ووك تبدأ من ([\d,]+) ج\.م، التاون هاوس من ([\d,]+) ج\.م، التوين هاوس من ([\d,]+) ج\.م، والفيلات المستقلة من ([\d,]+) ج\.م\. الأسعار استرشادية وقابلة للتغيير من المطور\.",
     r"Crescent Walk apartments start from EGP \1, townhouses from EGP \2, twin houses from EGP \3 and standalone villas from EGP \4. Prices are indicative and may be changed by the developer."),
    (r"<p class=\"faq-a\">مقدم يبدأ من (\d+)% وتقسيط حتى (\d+) سنين\.", r'<p class="faq-a">Down payment from \1% with installments up to \2 years.'),
    (r"مقدم (\d+)% وتقسيط يوصل لـ(\d+) سنين على وحدات Crescent Walk\. سيبلنا بياناتك ونرجعلك بأنسب الوحدات في حدود ميزانيتك\.",
     r"\1% down payment and installments up to \2 years on Crescent Walk units. Leave your details and we will come back with the best units within your budget."),
]
STRINGS = {
    "كريسنت ووك Crescent Walk من مراكز | شقق وفيلات التجمع السادس": "Crescent Walk 6th Settlement by Marakez | Apartments & Villas",
    "Crescent Walk — مراكز Marakez": "Crescent Walk — Marakez",
    "كريسنت ووك من مراكز": "Crescent Walk by Marakez",
    "مجتمع سكني وتجاري على 118 فدان في قلب شرق القاهرة": "A residential and retail community on 118 feddans in the heart of East Cairo",
    "احصل على أسعار Crescent Walk": "Get Crescent Walk prices",
    "أسعار كريسنت ووك والوحدات المتاحة": "Crescent Walk prices and available units",
    "كريسنت ووك — مجتمع متكامل على 118 فدان في قلب شرق القاهرة": "Crescent Walk — an integrated community on 118 feddans in the heart of East Cairo",
    " كريسنت ووك (Crescent Walk) مجتمع سكني وتجاري بتطويره <strong>مراكز</strong> على مساحة 118 فدان في قلب القاهرة الجديدة،": " Crescent Walk is a residential and retail community developed by <strong>Marakez</strong> on 118 feddans in the heart of New Cairo.",
    " بيجمع بين هدوء الخلوة وحيوية الوجهة الحضارية — مكان تقدر فيه ترتاح بعد يوم طويل وتعيش أجمل لحظاتك.": " It combines the calm of a retreat with the energy of an urban destination — a place to unwind after a long day and enjoy your best moments.",
    " تصميم المشروع مستوحى من روح حي الزمالك والمعادي، بمزيج متناغم بين الاتصال بالحياة والانتماء للمجتمع،": " The design is inspired by the spirit of Zamalek and Maadi, blending connection to city life with a sense of community",
    " من خلال ممرات خضراء حيوية تربط كل أجزاء المشروع. الموقع بيوفر وصول سهل لأهم المحاور الرئيسية": " through lively green corridors that link every part of the project. The location gives easy access to the main roads,",
    " زي العين السخنة وجنوب التسعين والرينج رود الأوسط.": " such as Ain Sokhna Road, South 90th Street and the Middle Ring Road.",
    "مرافق رئيسية متكاملة": "main integrated facilities",
    ">شرق<": ">East<",
    "القاهرة — التجمع السادس": "Cairo — 6th Settlement",
    "منشآت رياضية": "Sports facilities",
    "مول تجاري (Retail Plaza)": "Retail Plaza",
    "مناطق أنشطة": "Activity areas",
    "نادي اجتماعي (Clubhouse)": "Clubhouse",
    "احصل على قائمة أسعار كريسنت ووك": "Get the Crescent Walk price list",
    "موقع كريسنت ووك في التجمع السادس ومخطط المشروع": "Crescent Walk location in the 6th Settlement and master plan",
    "تعرّف على موقع المشروع الاستراتيجي وتوزيع المناطق والمرافق داخله": "See the project's strategic location and how its zones and facilities are laid out",
    "المخطط العام لمشروع كريسنت ووك (Crescent Walk) — التجمع السادس": "Crescent Walk master plan — 6th Settlement",
    " كريسنت ووك بيتمتع بموقع استراتيجي في قلب التجمع السادس بالقاهرة الجديدة، على مسافات قريبة\n من أهم المحاور الرئيسية زي العين السخنة وجنوب التسعين والرينج رود الأوسط، وده بيوفر وصول\n سهل وسريع من وإلى قلب القاهرة.": " Crescent Walk has a strategic location in the heart of the 6th Settlement in New Cairo, close to\n the main roads such as Ain Sokhna Road, South 90th Street and the Middle Ring Road, giving\n quick access to and from central Cairo.",
    ">العين السخنة<": ">Ain Sokhna Road<",
    ">جنوب التسعين<": ">South 90th Street<",
    ">الرينج رود الأوسط<": ">Middle Ring Road<",
    "جاليري Crescent Walk": "Crescent Walk gallery",
    "فيلا Crescent Walk بواجهة طوب ونخيل ومدخل مقوس في التجمع السادس": "Crescent Walk villa with a brick facade, palm trees and an arched entrance, 6th Settlement",
    "مبنى من ثلاثة أدوار بحديقة أمامية خضراء في Crescent Walk، التجمع السادس": "Three-storey building with a green front garden at Crescent Walk, 6th Settlement",
    "الواجهة الخلفية بتراسات وحديقة عشبية واسعة في Crescent Walk، التجمع السادس": "Rear facade with terraces and a wide lawn at Crescent Walk, 6th Settlement",
    "مبنى بمدخلين مقوسين وواجهة طوب ونخيل في Crescent Walk، التجمع السادس": "Building with two arched entrances, a brick facade and palm trees at Crescent Walk, 6th Settlement",
    "أسئلة شائعة عن كريسنت ووك (Crescent Walk)": "Frequently asked questions about Crescent Walk",
    "كريسنت ووك فين بالظبط؟": "Where exactly is Crescent Walk?",
    "كريسنت ووك (Crescent Walk) في قلب التجمع السادس بالقاهرة الجديدة، قريب من محاور العين السخنة وجنوب التسعين والرينج رود الأوسط.": "Crescent Walk is in the heart of the 6th Settlement in New Cairo, close to Ain Sokhna Road, South 90th Street and the Middle Ring Road.",
    "مين المطور بتاع كريسنت ووك؟": "Who is the developer of Crescent Walk?",
    "المطور هو مراكز (Marakez)، وهو نفس مطور District 5 في القاهرة الجديدة و Ramla في رأس الحكمة و Shams Soma في سوما باي.": "The developer is Marakez, which also developed District 5 in New Cairo, Ramla in Ras El Hekma and Shams Soma in Soma Bay.",
    "إيه أنواع الوحدات والمساحات في كريسنت ووك؟": "What unit types and sizes are available at Crescent Walk?",
    "أسعار كريسنت ووك بتبدأ من كام؟": "What do Crescent Walk prices start from?",
    "إيه أنظمة السداد في كريسنت ووك؟": "What are the payment plans at Crescent Walk?",
    "إيه المرافق والخدمات في كريسنت ووك؟": "What facilities and services does Crescent Walk have?",
    "المشروع على 118 فدان وفيه منشآت رياضية، مول تجاري (Retail Plaza)، مناطق أنشطة، ونادي اجتماعي (Clubhouse)، مع ممرات خضراء بتربط أجزاء المشروع.": "The project covers 118 feddans and includes sports facilities, a Retail Plaza, activity areas and a Clubhouse, with green corridors linking its parts.",
    "إيه الفرق بين كريسنت ووك وديستريكت 5؟": "What is the difference between Crescent Walk and District 5?",
    "الاتنين من تطوير مراكز في القاهرة الجديدة. كريسنت ووك (Crescent Walk) مجتمع سكني وتجاري على 118 فدان في التجمع السادس، وديستريكت 5&rlm; (District 5) مشروع متعدد الاستخدامات على 268 فدان وفيه شقق استلام فوري.": "Both are developed by Marakez in New Cairo. Crescent Walk is a residential and retail community on 118 feddans in the 6th Settlement, while District 5 is a mixed-use project on 268 feddans with ready-to-move apartments.",
    "شوف تفاصيل وأسعار ديستريكت 5": "See District 5 details and prices",
    "امتلك وحدتك في كريسنت ووك بأنسب الأنظمة": "Own your unit at Crescent Walk with the plan that suits you",
    "احصل على قائمة أسعار Crescent Walk وأنظمة التقسيط": "Get the Crescent Walk price list and payment plans",
}
