"""English text for district-5.html."""
REGEX = [
    (r"شقق ديستريكت 5 \(District 5\) من مراكز في القاهرة الجديدة — وحدات متشطبة، مقدم (\d+)% وتقسيط حتى (\d+) سنين، وعرض فوري التسليم بمقدم (\d+)%\. اطلب أحدث الأسعار الآن\.",
     r"District 5 by Marakez in New Cairo: finished apartments with a \1% down payment and installments up to \2 years, plus ready-to-move units with a \3% down payment. Request the latest prices."),
    (r"أيوه، فيه شقق استلام فوري في ديستريكت 5&rlm; \(District 5\) بمقدم (\d+)% وتقسيط على (\d+) سنين\.",
     r"Yes. District 5 has ready-to-move apartments with a \1% down payment and installments over \2 years."),
    (r"ديستريكت 5 في نيو كايرو \(القاهرة الجديدة\): (\d+) دقايق من طريق التسعين، (\d+) دقايق من الجامعة الأمريكية، (\d+) دقيقة من المعادي، و(\d+) دقيقة من المطار\.",
     r"District 5 is in New Cairo: \1 minutes from 90th Street, \2 minutes from the American University in Cairo, \3 minutes from Maadi and \4 minutes from Cairo Airport."),
    (r"ديستريكت 5 مشروع متعدد الاستخدامات على 268 فدان، والوحدات السكنية شقق متشطبة من (\d+) إلى (\d+) م²، من (\d+) إلى (\d+) غرف\.",
     r"District 5 is a mixed-use project on 268 feddans. Its homes are finished apartments from \1 to \2 m² with \3 to \4 bedrooms."),
    (r"أسعار شقق ديستريكت 5 تبدأ من ([\d,]+) ج\.م\. الأسعار استرشادية وقابلة للتغيير من المطور\.",
     r"District 5 apartments start from EGP \1. Prices are indicative and may be changed by the developer."),
    (r"نظامين: مقدم (\d+)% وتقسيط حتى (\d+) سنين، أو استلام فوري بمقدم (\d+)% وتقسيط على (\d+) سنين\.",
     r"Two plans: a \1% down payment with installments up to \2 years, or ready-to-move with a \3% down payment and installments over \4 years."),
    (r"مقدم (\d+)% وتقسيط يوصل لـ(\d+) سنين على وحدات District 5\. سيبلنا بياناتك ونرجعلك بأنسب الوحدات في حدود ميزانيتك\.",
     r"\1% down payment and installments up to \2 years on District 5 units. Leave your details and we will come back with the best units within your budget."),
    (r"طريق التسعين — (\d+) دقايق", r"90th Street — \1 minutes"),
    (r"الجامعة الأمريكية — (\d+) دقايق", r"AUC — \1 minutes"),
    (r"المعادي — (\d+) دقيقة", r"Maadi — \1 minutes"),
    (r"المطار — (\d+) دقيقة", r"Cairo Airport — \1 minutes"),
    (r"مصر الجديدة — (\d+) دقيقة", r"Heliopolis — \1 minutes"),
    (r"العين السخنة — (\d+) دقيقة", r"Ain Sokhna — \1 minutes"),
    (r"غرب القاهرة — (\d+) دقيقة", r"West Cairo — \1 minutes"),
]
STRINGS = {
    "ديستريكت 5 District 5 من مراكز | شقق القاهرة الجديدة واستلام فوري": "District 5 New Cairo by Marakez | Ready-to-Move Apartments",
    "District 5 — مراكز Marakez": "District 5 — Marakez",
    "ديستريكت 5 من مراكز": "District 5 by Marakez",
    "مشروع تجاري إداري سكني متكامل الخدمات في قلب القاهرة الجديدة": "A fully serviced residential, retail and office destination in the heart of New Cairo",
    "احصل على أسعار District 5": "Get District 5 prices",
    "أسعار ديستريكت 5 والوحدات المتاحة": "District 5 prices and available units",
    "اطلب أحدث الأسعار وأنظمة التقسيط لوحدات District 5": "Request the latest prices and payment plans for District 5 units",
    "متاح استلام فوري": "Ready to move",
    "متاح وحدات متشطبة": "Finished units",
    "&quot;استلام فوري&quot;": "&quot;Ready to move&quot;",
    "&quot;استلم وحدتك فورًا&quot;": "&quot;Move in right away&quot;",
    "&quot;أقل مقدم&quot;": "&quot;Lowest down payment&quot;",
    "&quot;ابدأ بأقل مقدم&quot;": "&quot;Start with the lowest down payment&quot;",
    "ديستريكت 5 — 5 رحلات في وجهة واحدة على 268 فدان": "District 5 — five journeys in one destination on 268 feddans",
    " ديستريكت 5&rlm; (District 5)، أو ديستريكت فايف، مشروع متعدد الاستخدامات بتطويره <strong>مراكز</strong> على مساحة 268 فدان في نيو كايرو،": " District 5 is a mixed-use project developed by <strong>Marakez</strong> on 268 feddans in New Cairo.",
    " بيجمع بين أسلوبي الحياة الحضري والضاحوي في مكان واحد: هدوء وخصوصية السكن، تجربة تسوق مميزة": " It brings urban and suburban living together in one place: quiet, private homes, distinctive shopping",
    " في D5M، ترفيه في Club5، ومساحات عمل في District5 Work — كل ده من غير ما تحتاج تتنقل بره المشروع.": " at D5M, leisure at Club5 and workspaces at District5 Work — all without leaving the project.",
    "رحلات في وجهة واحدة": "journeys in one destination",
    "مول تسوق (D5M)": "Shopping mall (D5M)",
    "نادي رياضي": "Sports club",
    "منطقة ترفيهية (LA7)": "Entertainment zone (LA7)",
    "مطاعم ومقاهي": "Restaurants and cafés",
    "احصل على قائمة أسعار ديستريكت 5": "Get the District 5 price list",
    "موقع ديستريكت 5 في القاهرة الجديدة ومخطط المشروع": "District 5 location in New Cairo and master plan",
    "تعرّف على موقع المشروع الاستراتيجي في نيو كايرو وتوزيع المناطق والمرافق داخله": "See the project's strategic location in New Cairo and how its zones and facilities are laid out",
    "المخطط العام لمشروع ديستريكت 5&rlm; (District 5) — القاهرة الجديدة": "District 5 master plan — New Cairo",
    " ديستريكت 5 بيتمتع بموقع استراتيجي في نيو كايرو، على مسافات قريبة من أهم المناطق والمحاور\n الرئيسية في القاهرة الكبرى، وده بيوفر وصول سهل وسريع من وإلى وسط البلد ومطار القاهرة.": " District 5 has a strategic location in New Cairo, close to the main districts and roads\n of Greater Cairo, with quick access to and from Downtown and Cairo Airport.",
    "جاليري District 5": "District 5 gallery",
    "عمارات District 5 بواجهات حجرية وبلكونات في القاهرة الجديدة": "District 5 buildings with stone facades and balconies, New Cairo",
    "مبنى سكني من أربعة أدوار ومدخل مظلل في District 5، القاهرة الجديدة": "Four-storey residential building with a shaded entrance at District 5, New Cairo",
    "ممشى مشجر ومقعد خشبي بجوار العمارات في District 5، القاهرة الجديدة": "Tree-lined walkway and wooden bench beside the buildings at District 5, New Cairo",
    "مقعد خشبي على ممشى منحني بين الأشجار في District 5، القاهرة الجديدة": "Wooden bench on a curved walkway among the trees at District 5, New Cairo",
    "مبانٍ منخفضة الارتفاع بين أشجار النخيل في District 5، القاهرة الجديدة": "Low-rise buildings among palm trees at District 5, New Cairo",
    "أسئلة شائعة عن ديستريكت 5&rlm; (District 5)": "Frequently asked questions about District 5",
    "هل فيه وحدات استلام فوري في ديستريكت 5؟": "Are there ready-to-move units at District 5?",
    "ديستريكت 5 فين بالظبط؟": "Where exactly is District 5?",
    "مين المطور بتاع ديستريكت 5؟": "Who is the developer of District 5?",
    "المطور هو مراكز (Marakez)، وهو نفس مطور Crescent Walk في التجمع السادس و Ramla في رأس الحكمة و Shams Soma في سوما باي.": "The developer is Marakez, which also developed Crescent Walk in the 6th Settlement, Ramla in Ras El Hekma and Shams Soma in Soma Bay.",
    "إيه أنواع الوحدات والمساحات في ديستريكت 5؟": "What unit types and sizes are available at District 5?",
    "أسعار ديستريكت 5 بتبدأ من كام؟": "What do District 5 prices start from?",
    "إيه أنظمة السداد في ديستريكت 5؟": "What are the payment plans at District 5?",
    "إيه المرافق والخدمات في ديستريكت 5؟": "What facilities and services does District 5 have?",
    "مول تسوق (D5M)، نادي رياضي، منطقة ترفيهية (LA7)، مطاعم ومقاهي، مساحات عمل District5 Work، و District5 Campus.": "A shopping mall (D5M), a sports club, an entertainment zone (LA7), restaurants and cafés, District5 Work offices and District5 Campus.",
    "إيه الفرق بين ديستريكت 5 وكريسنت ووك؟": "What is the difference between District 5 and Crescent Walk?",
    "الاتنين من تطوير مراكز في القاهرة الجديدة. ديستريكت 5&rlm; (District 5) مشروع متعدد الاستخدامات على 268 فدان وفيه شقق استلام فوري، وكريسنت ووك (Crescent Walk) مجتمع سكني وتجاري على 118 فدان في التجمع السادس.": "Both are developed by Marakez in New Cairo. District 5 is a mixed-use project on 268 feddans with ready-to-move apartments, while Crescent Walk is a residential and retail community on 118 feddans in the 6th Settlement.",
    "شوف تفاصيل وأسعار كريسنت ووك": "See Crescent Walk details and prices",
    "امتلك وحدتك في ديستريكت 5 بأنسب الأنظمة": "Own your unit at District 5 with the plan that suits you",
    "احصل على قائمة أسعار District 5 وأنظمة التقسيط": "Get the District 5 price list and payment plans",
}
