"""English text for ora-projects.html."""
REGEX = [
    (r" تأسست <strong>ORA Developers</strong> سنة (\d+) على يد رجل الأعمال م\. <strong>نجيب ساويرس</strong>، وخلال سنين قليلة",
     r" <strong>ORA Developers</strong> was founded in \1 by businessman Eng. <strong>Naguib Sawiris</strong>, and within a few years"),
    (r"Zed East و Solana East من ORA Developers في القاهرة الجديدة — وحدات متشطبة بالكامل، مقدم يبدأ من (\d+)% وتقسيط حتى (\d+) سنين\. اتصل بينا واعرف الأسعار المتاحة\.",
     r"Zed East and Solana East by ORA Developers in New Cairo: fully finished units with a down payment from \1% and installments up to \2 years. Contact us for current prices."),
    (r"وحدات متشطبة بالكامل، مقدم يبدأ من (\d+)% وتقسيط حتى (\d+) سنين\. اتصل بينا واعرف الأسعار المتاحة\.",
     r"Fully finished units with a down payment from \1% and installments up to \2 years. Contact us for current prices."),
    (r'(class="hr-cta oc-hero-wa" href="https://wa\.me/\d+\?text=)[^"]+"', r'\1Hello%2C%20I%20am%20interested%20in%20ORA%20projects%20(Zed%20East%20and%20Solana%20East)"'),
    (r'(class="oc-wa" href="https://wa\.me/\d+\?text=)[^"]*?(Zed%20East|Solana%20East)"', r'\1Hello%2C%20I%20would%20like%20details%20about%20\2"'),
    (r"<strong>(\d+) سنين</strong>", r"<strong>\1 years</strong>"),
    (r"شقق: (\d+) حتى (\d+) غرف", r"Apartments: \1 to \2 bedrooms"),
    (r"شقق متشطبة بالكامل بالتكييفات \(من غير كابينات المطبخ\)، والاستلام بعد ([\d.]+) سنة، مع خيارات تاون هاوس وتوين هاوس وستاند الون\.",
     r"offers fully finished apartments with air conditioning (without kitchen cabinets), delivery in \1 years, plus townhouse, twin house and standalone options."),
    (r"لشقة غرفة نوم واحدة — (\d+) م² \(Gardinn\)", r"for a one-bedroom apartment — \1 m² (Gardinn)"),
    (r"Zed East من ([\d,]+) ج\.م، و Solana East من ([\d,]+) ج\.م لشقة غرفة نوم واحدة (\d+) م² في مرحلة Gardinn\. الأسعار استرشادية وقابلة للتغيير من المطور\.",
     r"Zed East starts from EGP \1 and Solana East from EGP \2 for a one-bedroom \3 m² apartment in the Gardinn phase. Prices are indicative and may be changed by the developer."),
    (r"Zed East بمقدم يبدأ من (\d+)% وتقسيط حتى (\d+) سنين\. Solana East بـ (\d+)% مقدم \+ (\d+)% تعاقد وتقسيط حتى (\d+) سنين\.",
     r"Zed East: down payment from \1% with installments up to \2 years. Solana East: \3% down payment plus \4% on contract, with installments up to \5 years."),
    (r"مرحلة Gardinn في Solana East استلامها بعد ([\d.]+) سنة\.", r"The Gardinn phase at Solana East is delivered in \1 years."),
    (r"ORA Developers، اتأسست سنة (\d+) على يد م\. نجيب ساويرس\.", r"ORA Developers, founded in \1 by Eng. Naguib Sawiris."),
    (r" بقى عندها محفظة مشاريع في (\d+) دول — من مصر والإمارات لقبرص واليونان وجرينادا وباكستان والعراق\.",
     r" it built a portfolio of projects in \1 countries — from Egypt and the UAE to Cyprus, Greece, Grenada, Pakistan and Iraq."),
]
STRINGS = {
    " ORA بتتخصص في المجتمعات متعددة الاستخدامات بمواقع إستراتيجية، بتصميمات مبتكرة ومساحات خضراء واسعة": " ORA specializes in mixed-use communities in strategic locations, with innovative design, wide green spaces",
    " ومرافق عالمية المستوى.": " and world-class facilities.",
    "Zed East و Solana East من ORA | Global Marketing Real Estate": "Zed East & Solana East by ORA | Global Marketing Real Estate",
    "مشاريع ORA في القاهرة الجديدة – Zed East و Solana East": "ORA Projects in New Cairo – Zed East & Solana East",
    '"name": "مشاريع ORA"': '"name": "ORA Projects"',
    "ORA Developers — القاهرة الجديدة": "ORA Developers — New Cairo",
    "تملّك في مشاريع ORA": "Own a home in ORA projects",
    "Zed East و Solana East — وحدات متشطبة بالكامل في قلب القاهرة الجديدة": "Zed East and Solana East — fully finished units in the heart of New Cairo",
    "سنين تقسيط": "Years of installments",
    "تفاصيل أكثر - واتساب": "More details on WhatsApp",
    "ابعتلنا على الواتساب ونبعتلك الوحدات المتاحة وأنظمة السداد": "Message us on WhatsApp and we will send you available units and payment plans",
    "المشاريع المتاحة": "Available projects",
    "اختار المشروع المناسب ليك": "Choose the project that suits you",
    "كلمنا أو ابعتلنا واتساب ونبعتلك تفاصيل الوحدات والأسعار المتاحة": "Call or WhatsApp us and we will send you unit details and current prices",
    "فيلا Zed East حديثة بواجهات زجاجية وحديقة في القاهرة الجديدة": "Modern Zed East villa with glass facades and a garden, New Cairo",
    ">ستوديو<": ">Studio<",
    ">دوبلكس<": ">Duplex<",
    ">فوربلكس<": ">Fourplex<",
    ">ستاند الون<": ">Standalone<",
    "مشروع متكامل من ORA يجمع بين شقق Serviced بتشطيب كامل وتكييفات، ووحدات فاخرة زي الدوبلكس والفوربلكس والتاون هاوس والستاند الون.": "An integrated ORA project combining fully finished serviced apartments with air conditioning and premium units such as duplexes, fourplexes, townhouses and standalone villas.",
    "<small>ج.م</small>": "<small>EGP</small>",
    "أقل مقدم": "Lowest down payment",
    "أطول تقسيط": "Longest installment plan",
    "متشطب بالكامل": "Fully finished",
    ">التشطيب<": ">Finishing<",
    "اطلب تفاصيل Zed East": "Request Zed East details",
    "اتصل بخصوص Zed East": "Call about Zed East",
    "تصميم منازل Solana East المتصلة بحديقة خضراء في القاهرة الجديدة": "Solana East attached homes with a green garden, New Cairo",
    "<span>مرحلة <bdi>Gardinn</bdi> الجديدة</span>": "<span>New <bdi>Gardinn</bdi> phase</span>",
    "مجتمع سكني متكامل من ORA. المرحلة الجديدة <strong>Gardinn</strong>": "An integrated residential community by ORA. The new <strong>Gardinn</strong> phase",
    "مقدم + تعاقد": "Down payment + contract",
    "بالتكييفات": "With air conditioning",
    "اطلب تفاصيل Solana East": "Request Solana East details",
    "اتصل بخصوص Solana East": "Call about Solana East",
    "جاليري مشاريع ORA": "ORA projects gallery",
    "اتفرّج على Zed East من كل الزوايا": "See Zed East from every angle",
    "لقطة علوية لفيلات Zed East والمساحات الخضراء في القاهرة الجديدة": "Aerial view of Zed East villas and green spaces, New Cairo",
    "عمارات Zed East السكنية وممر مشجر عند الغروب في القاهرة الجديدة": "Zed East residential buildings and a tree-lined path at sunset, New Cairo",
    "فيلا Zed East بشرفة زجاجية وحديقة أمامية في القاهرة الجديدة": "Zed East villa with a glass balcony and front garden, New Cairo",
    "منازل Zed East متصلة بحدائق خلفية ومسابح في القاهرة الجديدة": "Zed East attached homes with back gardens and pools, New Cairo",
    "ساحة مفتوحة بين عمارات Zed East السكنية في القاهرة الجديدة": "Open plaza between Zed East residential buildings, New Cairo",
    "حديقة مركزية وممرات مشاة بين مباني Zed East في القاهرة الجديدة": "Central park and walkways between Zed East buildings, New Cairo",
    "المخطط العام لمشروع Zed East — القاهرة الجديدة": "Zed East master plan — New Cairo",
    "عن المطوّر": "About the developer",
    "ORA Developers — مجتمعات متكاملة بفلسفة السعادة": "ORA Developers — integrated communities built around happiness",
    "سنة التأسيس": "Year founded",
    "دول حول العالم": "countries worldwide",
    "مشاريع كبرى في مصر": "major projects in Egypt",
    "أبرز مشاريعها في مصر": "Key projects in Egypt",
    "ZED الشيخ زايد": "ZED Sheikh Zayed",
    "أسئلة شائعة عن Zed East و Solana East": "Frequently asked questions about Zed East and Solana East",
    "هل وحدات Zed East و Solana East متشطبة؟": "Are Zed East and Solana East units finished?",
    "أيوه، متشطبة بالكامل وبالتكييفات. شقق Zed East تشطيب كامل بالتكييفات (Serviced)، وشقق مرحلة Gardinn في Solana East متشطبة بالكامل بالتكييفات من غير كابينات المطبخ.": "Yes, they are fully finished with air conditioning. Zed East apartments are fully finished serviced units with air conditioning, and Gardinn phase apartments at Solana East are fully finished with air conditioning, without kitchen cabinets.",
    "Zed East و Solana East فين؟": "Where are Zed East and Solana East?",
    "المشروعين في القاهرة الجديدة.": "Both projects are in New Cairo.",
    "مين المطور؟": "Who is the developer?",
    "الأسعار بتبدأ من كام؟": "What do prices start from?",
    "إيه أنظمة السداد؟": "What are the payment plans?",
    "الاستلام إمتى في Solana East؟": "When is delivery at Solana East?",
    "رشّحلي وحدة": "Recommend a unit",
    "ملقتش الوحدة المناسبة ليك؟": "Did not find the right unit?",
    "اكتبلنا ميزانيتك — المقدم اللي جاهز تدفعه والقسط الشهري المريح ليك — ونبعتلك ترشيحاتنا المناسبة على الواتساب.": "Tell us your budget — the down payment you can pay and a comfortable monthly installment — and we will send suitable recommendations on WhatsApp.",
    "الاسم <em>": "Name <em>",
    "اكتب اسمك": "Your name",
    "رقم الموبايل <em>": "Mobile number <em>",
    '"01xxxxxxxxx"': '"+20 1xx xxx xxxx"',
    ">المشروع<": ">Project<",
    "مش متأكد — رشّحلي": "Not sure — recommend one",
    "المقدم المتاح": "Available down payment",
    "القسط الشهري": "Monthly installment",
    "<i>ج.م</i>": "<i>EGP</i>",
    "ابعتلنا ميزانيتك": "Send us your budget",
    "بتسجيلك بتوافق على <a": "By submitting you agree to the <a",
    "</a>. بياناتك بتروح لفريق المبيعات مباشرة.": "</a>. Your details go straight to the sales team.",
    "<strong>محمد احمد عبدالعزيز الصباغ</strong>": "<strong>Mohamed El Sabagh</strong>",
    "المعروضة، وجميع أسماء وشعارات المشاريع والمطوّرين (ومنها ORA Developers) مملوكة لأصحابها وتُستخدم لأغراض العرض والتعريف فقط.": "shown here. All project and developer names and logos (including ORA Developers) belong to their owners and are used for presentation and identification only.",
    "كافة البيانات من أسعار ومساحات وأنظمة سداد وصور هي": "All information, including prices, areas, payment plans and images, is",
}
