"""English text for privacy-policy.html."""
SIMPLE = True
REGEX = [
    (r'(class=pp-cta href="https://wa\.me/\d+\?text=)[^"]+"', r'\1Hello%2C%20I%20have%20a%20question%20about%20the%20privacy%20policy"'),
    (r"تواصل واتساب — (\d+)", r"Chat on WhatsApp — \1"),
]
STRINGS = {
    "سياسة الخصوصية | Global Marketing Real Estate": "Privacy Policy | Global Marketing Real Estate",
    "سياسة الخصوصية الخاصة بمنصة Global Marketing Real Estate، وكيفية جمع واستخدام وحماية بياناتك عند التواصل معنا بخصوص المشاريع العقارية.": "The Global Marketing Real Estate privacy policy: how we collect, use and protect your data when you contact us about real estate projects.",
    "الشفافية والأمان": "Transparency and security",
    "آخر تحديث: سبتمبر 2026": "Last updated: September 2026",
    " خصوصيتك تهمّنا. الصفحة دي بتوضّح إزاي بنجمع بياناتك ونستخدمها ونحميها لما تتواصل معانا": " Your privacy matters to us. This page explains how we collect, use and protect your data when you contact us",
    " أو تسيب بياناتك من خلال <strong>globalmarketingrealestate.com</strong>، اللي بيديره": " or leave your details through <strong>globalmarketingrealestate.com</strong>, operated by",
    "</strong> — المنصة الإعلامية التسويقية العقارية المستقلة اللي يملكها ويديرها <strong>محمد احمد عبدالعزيز الصباغ</strong>. باستخدامك للموقع،": "</strong> — the independent real estate marketing and media platform owned and operated by <strong>Mohamed El Sabagh</strong>. By using the website,",
    " بتوافق على الممارسات الموضّحة تحت.": " you agree to the practices described below.",
    "</span> البيانات اللي بنجمعها</h2>": "</span> Data we collect</h2>",
    "لما تسيب بياناتك أو تتواصل معانا، ممكن نجمع الآتي:": "When you leave your details or contact us, we may collect:",
    "<strong>بيانات التواصل:</strong> الاسم، رقم الموبايل / الواتساب، والإيميل لو أدخلته.": "<strong>Contact details:</strong> your name, mobile / WhatsApp number, and email if you provide it.",
    "<strong>بيانات الاهتمام:</strong> المشروع أو نوع الوحدة اللي بتسأل عنها والميزانية التقريبية.": "<strong>Interest details:</strong> the project or unit type you ask about and your approximate budget.",
    "<strong>بيانات تقنية:</strong> نوع الجهاز والمتصفح وصفحات الموقع اللي زرتها، بتتجمع أوتوماتيك لتحسين الخدمة.": "<strong>Technical data:</strong> device and browser type and the pages you visit, collected automatically to improve the service.",
    "</span> إزاي بنستخدم بياناتك</h2>": "</span> How we use your data</h2>",
    "بنستخدم البيانات للأغراض دي بس:": "We use the data only for these purposes:",
    "التواصل معاك للرد على استفسارك عن المشاريع العقارية.": "Contacting you to answer your enquiry about real estate projects.",
    "ترشيح وحدات أو مشاريع تناسب اهتمامك وميزانيتك.": "Recommending units or projects that match your interest and budget.",
    "إرسال تحديثات أو عروض متعلقة بالعقارات (تقدر توقفها في أي وقت).": "Sending property-related updates or offers (you can stop these at any time).",
    "تحسين تجربة الموقع وجودة الخدمة.": "Improving the website experience and service quality.",
    "</span> مشاركة البيانات</h2>": "</span> Data sharing</h2>",
    " إحنا <strong>مبنبيعش بياناتك</strong> لأي طرف. وبصفتنا منصة تسويقية عقارية مستقلة، ممكن نشارك بياناتك": " We <strong>do not sell your data</strong> to anyone. As an independent real estate marketing platform, we may share your data",
    " مع <strong>المطوّر العقاري صاحب المشروع اللي أنت مهتم بيه</strong> فقط عشان يتم استكمال": " only with <strong>the developer of the project you are interested in</strong>, in order to complete",
    " إجراءات الحجز أو الرد على استفسارك، وده في حدود الغرض اللي تواصلت علشانه بس.": " the reservation process or answer your enquiry, and only for the purpose you contacted us about.",
    "</span> الكوكيز (Cookies)</h2>": "</span> Cookies</h2>",
    " الموقع بيستخدم كوكيز بسيطة لتشغيل الصفحة بشكل صحيح وقياس أداء الحملات الإعلانية.": " The website uses basic cookies to run the page correctly and measure advertising campaign performance.",
    " تقدر تتحكم في الكوكيز من إعدادات المتصفح بتاعك، بس ملاحظة إن إيقافها ممكن يأثر على بعض وظائف الموقع.": " You can control cookies from your browser settings; note that disabling them may affect some website functions.",
    "</span> حماية بياناتك</h2>": "</span> Protecting your data</h2>",
    " بنتّخذ إجراءات تقنية وتنظيمية معقولة لحماية بياناتك من الوصول أو الاستخدام غير المصرّح به.": " We take reasonable technical and organizational measures to protect your data from unauthorized access or use.",
    " ومع إننا بنحرص على أعلى مستوى حماية، مفيش وسيلة نقل عبر الإنترنت مؤمّنة 100%،": " Although we aim for the highest level of protection, no method of transmission over the internet is 100% secure,",
    " فبنبذل أقصى جهد للحفاظ على سرية بياناتك.": " so we make every effort to keep your data confidential.",
    "</span> حقوقك</h2>": "</span> Your rights</h2>",
    "في أي وقت يحق لك:": "At any time you may:",
    "تطلب نسخة من البيانات اللي عندنا عنك.": "Request a copy of the data we hold about you.",
    "تطلب تعديل أو تصحيح بياناتك.": "Request that your data be amended or corrected.",
    "تطلب حذف بياناتك من سجلاتنا.": "Request that your data be deleted from our records.",
    "توقف استقبال الرسائل التسويقية.": "Stop receiving marketing messages.",
    "لممارسة أي من الحقوق دي، تواصل معانا على الواتساب الموضّح تحت.": "To exercise any of these rights, contact us on the WhatsApp number below.",
    "</span> تعديلات على السياسة</h2>": "</span> Changes to this policy</h2>",
    " ممكن نحدّث سياسة الخصوصية دي من وقت للتاني. أي تعديل هيتنشر على الصفحة دي مع تحديث تاريخ": " We may update this privacy policy from time to time. Any change will be published on this page with an updated",
    ' "آخر تحديث" في الأعلى، فيُفضّل مراجعتها بشكل دوري.': ' "Last updated" date at the top, so please review it periodically.',
    "عندك استفسار عن خصوصية بياناتك؟": "Have a question about your data privacy?",
    "إحنا تحت أمرك — تواصل معانا مباشرة على الواتساب.": "We are here to help — contact us directly on WhatsApp.",
}
