"""English text for ramla.html."""
REGEX = [
    (r"شاليهات وفيلات رملة \(Ramla\) من مراكز على بحر رأس الحكمة، الساحل الشمالي — مقدم (\d+)% وتقسيط حتى (\d+) سنين\. اطلب أحدث الأسعار وتفاصيل الوحدات المتاحة الآن\.",
     r"Ramla by Marakez on the Ras El Hekma coast, North Coast: chalets and villas with a \1% down payment and installments up to \2 years. Request the latest prices and available units."),
    (r"رملة \(Ramla\) على شاطئ رأس الحكمة في الساحل الشمالي: (\d+) دقايق من قيصر، (\d+) دقيقة من الماظة باي، و(\d+) دقيقة من هاسيندا ريد\.",
     r"Ramla is on the Ras El Hekma beach on Egypt's North Coast: \1 minutes from Caesar, \2 minutes from Almaza Bay and \3 minutes from Hacienda Red."),
    (r"وحدات رملة: شاليهات من ([\d,]+) إلى ([\d,]+) م²، تاون هاوس من ([\d,]+) إلى ([\d,]+) م²، توين هاوس من ([\d,]+) إلى ([\d,]+) م²، وفيلات مستقلة من ([\d,]+) إلى ([\d,]+) م²، وكلها متشطبة بالكامل\.",
     r"Ramla offers chalets from \1 to \2 m², townhouses from \3 to \4 m², twin houses from \5 to \6 m² and standalone villas from \7 to \8 m², all fully finished."),
    (r"أسعار شاليهات رملة تبدأ من ([\d,]+) ج\.م، التاون هاوس من ([\d,]+) ج\.م، التوين هاوس من ([\d,]+) ج\.م، والفيلات المستقلة من ([\d,]+) ج\.م\. الأسعار استرشادية وقابلة للتغيير من المطور\.",
     r"Ramla chalets start from EGP \1, townhouses from EGP \2, twin houses from EGP \3 and standalone villas from EGP \4. Prices are indicative and may be changed by the developer."),
    (r"مقدم يبدأ من (\d+)% وتقسيط حتى (\d+) سنين\.", r"Down payment from \1% with installments up to \2 years."),
    (r"شاطئ رملي بطول ([\d.]+) كم، بحيرة صناعية \(Lagoon\)، فندق، مجمع رياضي، مزرعة مجتمعية، وشارع القرية \(Village Street\)\.",
     r"A \1 km sandy beach, a lagoon, a hotel, a sports complex, a community farm and Village Street."),
    (r"مقدم (\d+)% وتقسيط يوصل لـ(\d+) سنين على وحدات Ramla\. سيبلنا بياناتك ونرجعلك بأنسب الوحدات في حدود ميزانيتك\.",
     r"\1% down payment and installments up to \2 years on Ramla units. Leave your details and we will come back with the best units within your budget."),
    (r"منزلك الحصري على شاطئ رأس الحكمة — ([\d.]+) كم من الرمال البيضاء", r"Your exclusive home on the Ras El Hekma beach — \1 km of white sand"),
    (r"قيصر — (\d+) دقايق", r"Caesar — \1 minutes"),
    (r"الماظة باي — (\d+) دقيقة", r"Almaza Bay — \1 minutes"),
    (r"هاسيندا ريد — (\d+) دقيقة", r"Hacienda Red — \1 minutes"),
    (r" يمتد على ([\d.]+) كيلومتر، وتصميم بيوازن بين الخصوصية والحياة المجتمعية النابضة\.",
     r" stretching \1 kilometers, designed to balance privacy with a lively community."),
]
STRINGS = {
    "رملة Ramla رأس الحكمة من مراكز | أسعار الشاليهات والفيلات": "Ramla Ras El Hekma by Marakez | Chalets & Villas Prices",
    "Ramla — الساحل الشمالي": "Ramla — North Coast",
    "رملة من مراكز": "Ramla by Marakez",
    "احصل على أسعار Ramla": "Get Ramla prices",
    "أسعار رملة رأس الحكمة والوحدات المتاحة": "Ramla Ras El Hekma prices and available units",
    "رملة — الوجهة الساحلية الحصرية على شاطئ رأس الحكمة": "Ramla — the exclusive coastal destination on the Ras El Hekma beach",
    " رملة (Ramla) هي الوجهة الساحلية المتكاملة لـ<strong>مراكز</strong> على بحر رأس الحكمة، بشاطئ رملي أبيض": " Ramla is the integrated coastal destination by <strong>Marakez</strong> in Ras El Hekma, with a white sandy beach",
    " المشروع بيضم حيين سكنيين متكاملين: <strong>The Town</strong> بممرات ومسارات تربط الفيلات الخاصة،": " The project has two residential neighborhoods: <strong>The Town</strong>, with walkways linking private villas,",
    " و<strong>The Grove</strong> بمساحاته الخضراء الواسعة وفلله الأكبر.": " and <strong>The Grove</strong>, with wide green spaces and larger villas.",
    "كم طول الشاطئ الرملي": "km of sandy beach",
    "دقيقة من الماظة باي": "minutes from Almaza Bay",
    "بحيرة صناعية (Lagoon)": "Lagoon",
    ">فندق<": ">Hotel<",
    "مجمع رياضي": "Sports complex",
    "مزرعة مجتمعية": "Community farm",
    "شارع القرية (Village Street)": "Village Street",
    "الأحياء السكنية": "Neighborhoods",
    "شركاء المشروع": "Project partners",
    "احصل على قائمة أسعار رملة": "Get the Ramla price list",
    "موقع رملة في رأس الحكمة ومخطط المشروع": "Ramla location in Ras El Hekma and master plan",
    "تعرّف على موقع المشروع على الساحل الشمالي وتوزيع الأحياء والمرافق داخله": "See where the project sits on the North Coast and how its neighborhoods and facilities are laid out",
    "المخطط العام لمشروع رملة (Ramla) — رأس الحكمة، الساحل الشمالي": "Ramla master plan — Ras El Hekma, North Coast",
    " رملة موقعها على شاطئ رأس الحكمة بيجمع بين الخصوصية وقرب المسافات لأهم الوجهات على\n الساحل الشمالي، وده بيخليها وجهة سهل توصلها في وقت قليل من أهم المناطق المجاورة.": " Ramla's location on the Ras El Hekma beach combines privacy with short distances to the main\n destinations on the North Coast, so it is quick to reach from the key nearby areas.",
    "جاليري Ramla": "Ramla gallery",
    "فيلا Ramla بحمام سباحة وتراس مضاء ليلًا في رأس الحكمة، الساحل الشمالي": "Ramla villa with a pool and a lit terrace at night, Ras El Hekma, North Coast",
    "صالة معيشة مطلة على البحر في فيلا Ramla، رأس الحكمة، الساحل الشمالي": "Sea-view living room in a Ramla villa, Ras El Hekma, North Coast",
    "سباحة في مياه البحر الصافية على شاطئ Ramla، رأس الحكمة، الساحل الشمالي": "Swimming in clear sea water at Ramla beach, Ras El Hekma, North Coast",
    "لقطة جوية لشاطئ Ramla ومظلاته في رأس الحكمة، الساحل الشمالي": "Aerial view of Ramla beach and its umbrellas, Ras El Hekma, North Coast",
    "شاطئ رملي بمظلات وصخور طبيعية في Ramla، رأس الحكمة، الساحل الشمالي": "Sandy beach with umbrellas and natural rocks at Ramla, Ras El Hekma, North Coast",
    "زوار بجوار خيمة شاطئ خشبية على رمال Ramla، رأس الحكمة، الساحل الشمالي": "Visitors beside a wooden beach hut on the sand at Ramla, Ras El Hekma, North Coast",
    "واجهة فيلا Ramla بسور حجري وبوابة خشبية في رأس الحكمة، الساحل الشمالي": "Ramla villa facade with a stone wall and wooden gate, Ras El Hekma, North Coast",
    "تجمع عند الغروب تحت مظلة خشبية في Ramla، رأس الحكمة، الساحل الشمالي": "Sunset gathering under a wooden pergola at Ramla, Ras El Hekma, North Coast",
    "مطبوعة تعاون Azza Fahmy مع Ramla Beach Club في رأس الحكمة، الساحل الشمالي": "Azza Fahmy collaboration print for Ramla Beach Club, Ras El Hekma, North Coast",
    "أسئلة شائعة عن رملة (Ramla) رأس الحكمة": "Frequently asked questions about Ramla Ras El Hekma",
    "رملة فين بالظبط؟": "Where exactly is Ramla?",
    "مين المطور بتاع رملة؟": "Who is the developer of Ramla?",
    "المطور هو مراكز (Marakez)، وهو نفس مطور District 5 و Crescent Walk في القاهرة الجديدة و Shams Soma في سوما باي.": "The developer is Marakez, which also developed District 5 and Crescent Walk in New Cairo and Shams Soma in Soma Bay.",
    "إيه أنواع الوحدات والمساحات في رملة؟": "What unit types and sizes are available at Ramla?",
    "أسعار رملة بتبدأ من كام؟": "What do Ramla prices start from?",
    "إيه أنظمة السداد في رملة؟": "What are the payment plans at Ramla?",
    "إيه المرافق والخدمات في رملة؟": "What facilities and services does Ramla have?",
    "إيه الفرق بين رملة وشمس سوما؟": "What is the difference between Ramla and Shams Soma?",
    "الاتنين من تطوير مراكز. رملة (Ramla) في رأس الحكمة على الساحل الشمالي، وشمس سوما (Shams Soma) في سوما باي على البحر الأحمر.": "Both are developed by Marakez. Ramla is in Ras El Hekma on the North Coast, while Shams Soma is in Soma Bay on the Red Sea.",
    "شوف تفاصيل وأسعار شمس سوما": "See Shams Soma details and prices",
    "امتلك وحدتك في رملة على بحر رأس الحكمة": "Own your unit at Ramla on the Ras El Hekma coast",
    "احصل على قائمة أسعار Ramla وأنظمة التقسيط": "Get the Ramla price list and payment plans",
}
