"""English text for shams-soma.html."""
REGEX = [
    (r"شمس سوما \(Shams Soma\) أحدث مشاريع مراكز في سوما باي على البحر الأحمر — شقق وشاليهات، تاون هاوس وفيلات بمقدم (\d+)% وتقسيط حتى (\d+) سنين\. اطلب أسعار شمس سوما الآن\.",
     r"Shams Soma, the latest Marakez project in Soma Bay on the Red Sea: apartments and chalets, townhouses and villas with a \1% down payment and installments up to \2 years. Request Shams Soma prices now."),
    (r"في مرحلة Family &amp; Friends متاح في شمس سوما (\d+) نوع وحدة بين شقق وشاليهات وتاون هاوس وفيلات مستقلة، والمساحات المبنية من (\d+) إلى (\d+) م²\.",
     r"In the Family &amp; Friends phase, Shams Soma offers \1 unit types across apartments and chalets, townhouses and standalone villas, with built-up areas from \2 to \3 m²."),
    (r"أسعار الشقق والشاليهات في شمس سوما تبدأ من ([\d,]+) ج\.م، التاون هاوس من ([\d,]+) ج\.م، والفيلات المستقلة من ([\d,]+) ج\.م\. الأسعار استرشادية وقابلة للتغيير من المطور\.",
     r"Shams Soma apartments and chalets start from EGP \1, townhouses from EGP \2 and standalone villas from EGP \3. Prices are indicative and may be changed by the developer."),
    (r"نظامين: (\d+)% مقدم \+ (\d+)% بعد (\d+) شهور والباقي على (\d+) سنين، أو (\d+)% مقدم والباقي على (\d+) سنين\. جدية الحجز ([\d,]+) ج\.م للشقق والشاليهات و([\d,]+) ج\.م للفيلات والتاون هاوس\.",
     r"Two plans: \1% down payment plus \2% after \3 months with the balance over \4 years, or \5% down payment with the balance over \6 years. The expression of interest (EOI) is EGP \7 for apartments and chalets and EGP \8 for villas and townhouses."),
    (r"مقدم (\d+)% وتقسيط يوصل لـ(\d+) سنين على وحدات Shams Soma\. سيبلنا بياناتك ونرجعلك بأنسب الوحدات في حدود ميزانيتك\.",
     r"\1% down payment and installments up to \2 years on Shams Soma units. Leave your details and we will come back with the best units within your budget."),
    (r"</span> إضافية بعد (\d+) شهور، والباقي على <span class=\"mkzt-term-num\">(\d+) سنين</span> \((\d+) قسط متساوي\)",
     r'</span> more after \1 months, with the balance over <span class="mkzt-term-num">\2 years</span> (\3 equal installments)'),
    (r"</span> مقدم، والباقي على <span class=\"mkzt-term-num\">(\d+) سنين</span> \((\d+) قسط متساوي\)",
     r'</span> down payment, with the balance over <span class="mkzt-term-num">\1 years</span> (\2 equal installments)'),
]
STRINGS = {
    "شمس سوما Shams Soma من مراكز | شاليهات وفيلات سوما باي": "Shams Soma by Marakez | Chalets & Villas in Soma Bay",
    "Shams Soma — سوما باي، البحر الأحمر": "Shams Soma — Soma Bay, Red Sea",
    "شمس سوما من مراكز": "Shams Soma by Marakez",
    "إطلالة جديدة تشرق على سوما باي — أحدث وجهات مراكز الساحلية على البحر الأحمر": "A new horizon rising over Soma Bay — the latest Marakez coastal destination on the Red Sea",
    "احصل على أسعار Shams Soma": "Get Shams Soma prices",
    "أسعار شمس سوما والوحدات المتاحة": "Shams Soma prices and available units",
    "اطلب تفاصيل مرحلة Family &amp; Friends وأسعار الوحدات المتاحة الآن": "Request the Family &amp; Friends phase details and current unit prices",
    "لونش جديد": "New launch",
    "أحدث لونش من مراكز على البحر الأحمر — سجّل اهتمامك من مرحلة Family &amp; Friends": "The latest Marakez launch on the Red Sea — register your interest from the Family &amp; Friends phase",
    "شقق وشاليهات": "Apartments & Chalets",
    "شمس سوما من مراكز — حياة ساحلية جديدة في سوما باي": "Shams Soma by Marakez — a new coastal lifestyle in Soma Bay",
    " شمس سوما (Shams Soma) هي أحدث مشاريع <strong>مراكز</strong> على البحر الأحمر، بتقدّم تعبير جديد عن الحياة": " Shams Soma is the latest <strong>Marakez</strong> project on the Red Sea, offering a fresh take on coastal",
    " الساحلية في قلب سوما باي — من أرسخ الوجهات الساحلية بالغردقة. المشروع لسه في مراحله": " living in the heart of Soma Bay, one of Hurghada's most established coastal destinations. The project is still in its",
    " الأولى (مرحلة Family &amp; Friends التمهيدية قبل الإطلاق العام)، وتفاصيل المساحات والمرافق": " early stages (the Family &amp; Friends pre-launch phase), and final details of sizes and facilities",
    " النهائية هتتحدث تباعًا من المطوّر أول ما تُعتمد رسميًا.": " will be updated by the developer as soon as they are officially approved.",
    "نوع وحدة متاح في هذه المرحلة": "unit types available in this phase",
    "م² نطاق المساحات المبنية": "m² built-up area range",
    "أنظمة سداد متاحة": "payment plans available",
    "مرحلة Family &amp; Friends": "Family &amp; Friends phase",
    "احصل على قائمة أسعار شمس سوما": "Get the Shams Soma price list",
    "موقع شمس سوما في سوما باي ومخطط المشروع": "Shams Soma location in Soma Bay and master plan",
    "تعرّف على موقع المشروع في سوما باي وأقرب المعالم والوجهات": "See where the project sits in Soma Bay and the nearest landmarks",
    "المخطط العام لمشروع شمس سوما (Shams Soma) — سوما باي، البحر الأحمر": "Shams Soma master plan — Soma Bay, Red Sea",
    " شمس سوما بتقع في قلب سوما باي على البحر الأحمر، من أرسخ الوجهات السياحية والسكنية\n بالغردقة، وقريبة من أهم المرافق الترفيهية والرياضية والتعليمية في المنطقة.": " Shams Soma sits in the heart of Soma Bay on the Red Sea, one of Hurghada's most established resort and residential\n destinations, close to the area's main leisure, sports and education facilities.",
    "معالم ووجهات قريبة": "Nearby landmarks",
    ">أنظمة السداد<": ">Payment plans<",
    "أنظمة السداد وجدية الحجز": "Payment plans and expression of interest",
    "تفاصيل الأسعار الكاملة بتتبعت مع فريق المبيعات بعد تسجيل بياناتك": "Full pricing details are sent by the sales team after you register",
    "نظام السداد — الخيار الأول": "Payment plan — option one",
    "نظام السداد — الخيار الثاني": "Payment plan — option two",
    "</span> مقدم + <span": "</span> down payment + <span",
    "جدية حجز (EOI)": "Expression of interest (EOI)",
    "الشقق والشاليهات: <span": "Apartments and chalets: <span",
    "</span> ج.م — الفيلات والتاون هاوس: <span": "</span> EGP — villas and townhouses: <span",
    "</span> ج.م</p>": "</span> EGP</p>",
    "جاليري Shams Soma": "Shams Soma gallery",
    "لمحة أولى من المشروع خلال مرحلة Family &amp; Friends": "A first look at the project during the Family &amp; Friends phase",
    "مسبح مطل على البحر في Shams Soma، سوما باي، البحر الأحمر": "Sea-view pool at Shams Soma, Soma Bay, Red Sea",
    "فيلا صفراء بحمام سباحة خاص وحديقة في Shams Soma، سوما باي، البحر الأحمر": "Yellow villa with a private pool and garden at Shams Soma, Soma Bay, Red Sea",
    "تراس طعام مظلل وحديقة صبار في Shams Soma، سوما باي، البحر الأحمر": "Shaded dining terrace and cactus garden at Shams Soma, Soma Bay, Red Sea",
    "تراس بمسبح صغير وجلسة مظللة في Shams Soma، سوما باي، البحر الأحمر": "Terrace with a plunge pool and shaded seating at Shams Soma, Soma Bay, Red Sea",
    "مياه صافية وشعاب مرجانية قرب Shams Soma، سوما باي، البحر الأحمر": "Clear water and coral reefs near Shams Soma, Soma Bay, Red Sea",
    "أسئلة شائعة عن شمس سوما (Shams Soma)": "Frequently asked questions about Shams Soma",
    "شمس سوما فين بالظبط؟": "Where exactly is Shams Soma?",
    "شمس سوما (Shams Soma) في قلب سوما باي على البحر الأحمر بالغردقة، قريبة من The Cascades Golf Resort و Soma Bay Marina و GEMS International School Soma Bay.": "Shams Soma is in the heart of Soma Bay on the Red Sea in Hurghada, close to The Cascades Golf Resort, Soma Bay Marina and GEMS International School Soma Bay.",
    "مين المطور بتاع شمس سوما؟": "Who is the developer of Shams Soma?",
    "المطور هو مراكز (Marakez)، وشمس سوما هي مشروع مراكز على البحر الأحمر. مراكز هي نفس مطور District 5 و Crescent Walk في القاهرة الجديدة و Ramla في رأس الحكمة.": "The developer is Marakez, and Shams Soma is its Red Sea project. Marakez also developed District 5 and Crescent Walk in New Cairo and Ramla in Ras El Hekma.",
    "إيه أنواع الوحدات في شمس سوما؟ شاليهات ولا فيلات؟": "What unit types does Shams Soma offer? Chalets or villas?",
    "أسعار شمس سوما بتبدأ من كام؟": "What do Shams Soma prices start from?",
    "إيه أنظمة السداد في شمس سوما؟": "What are the payment plans at Shams Soma?",
    "إيه المرافق والخدمات في شمس سوما؟": "What facilities and services does Shams Soma have?",
    "تفاصيل مرافق المشروع النهائية هتتعلن من المطوّر بعد اعتمادها. وحوالين المشروع في سوما باي: ملاعب جولف، Soma Bay Marina، Soma Sports Club، و Soma Tennis Academy.": "The developer will announce the project's final facilities once they are approved. Around the project in Soma Bay you will find golf courses, Soma Bay Marina, Soma Sports Club and Soma Tennis Academy.",
    "إيه الفرق بين شمس سوما ورملة؟": "What is the difference between Shams Soma and Ramla?",
    "الاتنين من تطوير مراكز. شمس سوما في سوما باي على البحر الأحمر، ورملة (Ramla) في رأس الحكمة على الساحل الشمالي.": "Both are developed by Marakez. Shams Soma is in Soma Bay on the Red Sea, while Ramla is in Ras El Hekma on the North Coast.",
    "شوف تفاصيل وأسعار Ramla": "See Ramla details and prices",
    "امتلك وحدتك في شمس سوما بأنسب الأنظمة": "Own your unit at Shams Soma with the plan that suits you",
    "احصل على قائمة أسعار Shams Soma وأنظمة التقسيط": "Get the Shams Soma price list and payment plans",
    " خصوصًا بيانات هذه الصفحة الخاصة بمرحلة Family &amp; Friends التمهيدية قبل الإطلاق العام، والتي": " This applies especially to this page's Family &amp; Friends pre-launch information, which",
    " قد تختلف عن الأسعار والتفاصيل النهائية عند الإطلاق الرسمي. يُرجى الرجوع للمطوّر الرسمي لاعتماد": " may differ from final prices and details at the official launch. Please confirm final prices and details",
    " الأسعار والتفاصيل النهائية قبل اتخاذ أي قرار شرائي.": " with the official developer before making any purchase decision.",
}
